name: Docker Image CI

on:
  push:
    branches: [ "16.0" ]
  pull_request:
    branches: [ "16.0" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Odoo 16
      run: docker build . --file Dockerfile --tag lambertinny/odoo-16:$GITHUB_RUN_NUMBER
      
    - name: Docker Push
      run: docker push lambertinny/odoo-16:$GITHUB_RUN_NUMBER
